### ISSUE TITLE
BBR2 failing on 5.10 ARM32

### ISSUE THREAD

**Issue by V10lator** [sirlucjan/kernel-patches#5]
This patch is failing to link on ARM32: https://github.com/sirlucjan/kernel-patches/blob/master/5.10/bbr2-patches-v3/0001-bbr2-5.10-introduce-BBRv2.patch

```
  LD      .tmp_vmlinux.kallsyms1
ld: net/ipv4/tcp_bbr2.o: in function `bbr_tso_segs':
tcp_bbr2.c:(.text+0x50): undefined reference to `__aeabi_uldivmod'
ld: net/ipv4/tcp_bbr2.o: in function `bbr_quantization_budget':
tcp_bbr2.c:(.text+0x3cc): undefined reference to `__aeabi_uldivmod'
ld: net/ipv4/tcp_bbr2.o: in function `bbr_debug':
tcp_bbr2.c:(.text+0xa18): undefined reference to `__aeabi_uldivmod'
ld: tcp_bbr2.c:(.text+0xe60): undefined reference to `__aeabi_uldivmod'
ld: net/ipv4/tcp_bbr2.o: in function `bbr2_handle_queue_too_high_in_startup':
tcp_bbr2.c:(.text+0x1104): undefined reference to `__aeabi_uldivmod'
ld: net/ipv4/tcp_bbr2.o:tcp_bbr2.c:(.text+0x15cc): more undefined references to `__aeabi_uldivmod' follow
make: *** [Makefile:1178: vmlinux] Fehler 
```

Note that 5.10 is the curent raspberry pi kernel: https://github.com/raspberrypi/linux

**Comment by sirlucjan** [comment]
Unfortunately, I don't have the right hardware to compile this on the ARM32 architecture. At the time I compiled this on a 64 bit standard processor and didn't get any of the above errors. I have no way of adapting this code to the architecture you mention - besides I don't use 5.10 kernel for a long time (currently I use 5.13 and 5.14) so I don't even know if this patch works on current 5.10 kernel. I don't support LTS kernels - I always rely on the newest ones.
