### ISSUE TITLE
SpadFS no build with kernel 5.18

### ISSUE THREAD

**Issue by manualinux** [sirlucjan/kernel-patches#10]
Hello,

Patch 0001-spadfs-5.18-merge-v1.0.15.patch is not compatible with kernel 5.18. The error displayed in the console is as follows when compiling the kernel:

```
fs/spadfs/buffer.c:92:120: error: too few arguments to function call, expected 4, have 2
  bio = bio_alloc((((( gfp_t)(0x400u|0x800u))) & ~(( gfp_t)0x400u)) | (( gfp_t)0x10000u) | (( gfp_t)0x2000u), bio_pages);
        ~~~~~~~~~                                                                                                      ^
./include/linux/bio.h:423:127: note: 'bio_alloc' declared here
static inline __attribute__((__gnu_inline__)) __attribute__((__unused__)) __attribute__((no_instrument_function)) struct bio *bio_alloc(struct block_device *bdev,
                                                                                                                              ^
```
I have contacted the developer of SpadFS and he has provided me with the link to the git repository of the development version that is compatible with version 5.18: git://leontynka.twibright.com/spadfs.git. I have updated the patch from that version, which I include in this post. As I had known about this file system through your project, I think it was only fair to let you know about it.

[spadfs-5.18.patch.gz](https://github.com/sirlucjan/kernel-patches/files/8761762/spadfs-5.18.patch.gz)

Regards

**Comment by sirlucjan** [comment]
Merged: https://github.com/sirlucjan/kernel-patches/commit/f4096a070ed86cf6acf289cc5275576cb626f667

Thanks a lot!

**Comment by manualinux** [comment]
I am reopening this because this file system does not work correctly with kernel 5.18. Files or directories that are deleted or moved to another file system from a SpadFS partition are loaded into system memory and remain there permanently. I have already communicated this to the SpadFS developer, but I have not yet received a reply. 

This morning I updated the local SpadFS repository and found that two changes were made to the file.c and super.c files. I updated the patch, compiled the module and found that this is now resolved. So I leave the patch updated and hope all is well.

Regards

[spadfs-5.18_v2.patch.gz](https://github.com/sirlucjan/kernel-patches/files/8784211/spadfs-5.18_v2.patch.gz)

**Comment by manualinux** [comment]
I will leave the issue open until there is a working version. That revision is the same one I have and it gives problems.

Regards

**Comment by manualinux** [comment]
I consider the incident resolved. It was a compilation problem with my custom kernel and ccache. The latest code revision of SpadFS is functional.

Regards

**Comment by manualinux** [comment]
The NTFS3 kernel driver had the same problem as SpadFS, hence, I kept insisting that the problem was not solved. The problem is that it only failed when moving content between a SpadFS partition and an NTFS partition, not with other linux partitions and an NTFS partition. More information on this [link](https://lore.kernel.org/ntfs3/CAKYAXd-BZK9iG-Od0-60eFOjQ76uSfOJit6k13bR96A_o-wCwA@mail.gmail.com/T/#t).

I close definitively the issue, I think it was appropriate to introduce this clarification.

Regards.

**Comment by sirlucjan** [comment]
@manualinux 

SpadFS 1.0.16:

https://github.com/sirlucjan/kernel-patches/commit/e43f7d4e022f03ec7c4391d04e7eff76a98f9472
